rootProject.name = "project"
include("ContentLoaderAdapter")
include("ContentProcessor")
include("contentProcessor")
include("contentProcessor")
include("contentProcessor")
include("ContentProcessor")
include("contentProcess")
include("common-dto")
include("priceHistory")
include("notificationSender")