server:
  port: 8080

spring:
  application:
    name: CoreCRM
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

jpa:
  generate-ddl: true
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql: true
  show-sql: true