spring:
  application:
    name: ContentLoaderAdapter
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: ${KF_TOPIC}

server:
  port: 8080