apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  password: MTIz
---
apiVersion: v1
kind: Secret
metadata:
  name: mail-secrets
type: Opaque
data:
  username: dGltb2ZlaS50aW1vc2hlbmtvQHlhbmRleC5ydQo=
  password: dWN3a2h2emlxaXhpbmxyYQ==
